#!/bin/sh

wombo=$1

echo '' && echo 'Loading Reviews' 1>&2 && curl -s $(curl -vs $(archive echo "$wombo" _reviews.xml) 2>&1 | grep '< location:' | awk '{print $3}' | tr -d '\r') | sed 's/<?xml version="1.0" encoding="UTF-8"?>//; /<reviews itemIdentifier=/d; /<review>/d; s/<\/review>//g; s/<reviewtitle>/Title: /g; s/<\/reviewtitle>//g; s/<reviewer>/User: /g; s/<\/reviewer>//g; s/<reviewbody>/Review: /g; s/<\/reviewbody>//g; s/<stars>/Stars: /g; s/<\/stars>//g; s/<reviewdate>/Review date: /g; s/<\/reviewdate>//g; s/<createdate>/Creation date: /g; s/<\/createdate>//g; s/<reviewer_itemname>/User ID: /g; s/<\/reviewer_itemname>//g; s/<info>/info/g; s/<num_reviews>/Number of Reviews: /g; s/<\/num_reviews>//g; s/<avg_rating>/Avg Number of Reviews: /g; s/<\/avg_rating>//g; s/<\/info>//g; s/<\/reviews>//g' > archivervs-temp.txt && more archivervs-temp.txt && rm archivervs-temp.txt && echo ''
